services: docker
language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      install:
        - cpanm --notest --installdeps .
      script:
        - cpanm -v --test-only .

    - stage: 🐳 Docker
      if: branch = master
      script:
        # DOCKER_USER and $DOCKER_PASS are set in the Travis settings for the project.
        - docker build --pull -t $DOCKER_USER/pg_prove:latest -t $DOCKER_USER/pg_prove:$(perl bin/pg_prove -V | awk '{print $2}') -f dist/Dockerfile .
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - docker push $DOCKER_USER/pg_prove
        - docker images
